### ISSUE TITLE
"Package name com.sri-mobile is invalid"

### ISSUE THREAD

**Issue by mkotsbak** [chandu0101/sri#15]
```
$sri/mobile-examples$ react-native android
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Package name com.sri-mobile is invalid
    at [object Object].module.exports.yeoman.generators.NamedBase.extend.initializing [...]
```

This is most likely caused by a hyphen (‐) in the package name. It could be replaced by an underscore (_).

**Comment by ferologics** [comment]
I'm having the same issue after renaming the project

``` bash
react-native upgrade
Upgrading project to react-native v0.31.0
Be sure to read the release notes and breaking changes:
https://github.com/facebook/react-native/releases/tag/v0.31.0
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Package name com.nrf5x-rf-validation-mobile-app is invalid
    at module.exports.yeoman.generators.NamedBase.extend.initializing (index.js:41:13)
    at /Users/master/Estimote/nRF5x-RF-Validation-Mobile-App/node_modules/yeoman-generator/lib/base.js:430:16
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)
```
