### ISSUE TITLE
TimeoutError on building mobile example

### ISSUE THREAD

**Issue by hamazy** [chandu0101/sri#38]
Hi,

I encountered `TimeoutError` when I tried to run the mobile example included in this project.

```
$ node node_modules/react-native/local-cli/cli.js start --reset-cache
......
[11:39:04 PM] <START> request:/index.ios.bundle?platform=ios&dev=true&hot=true
[11:39:04 PM] <START> find dependencies
Error: TimeoutError: transforming /Users/hamazy/Documents/programming/javascript/sri/mobile-examples/index.ios.js took longer than 301 seconds.
You can adjust timeout via the 'transformTimeoutInterval' option
    at index.js:101:30
    at tryCallOne (/Users/hamazy/Documents/programming/javascript/sri/mobile-examples/node_modules/promise/lib/core.js:37:12)
    at /Users/hamazy/Documents/programming/javascript/sri/mobile-examples/node_modules/promise/lib/core.js:123:15
    at flush (/Users/hamazy/Documents/programming/javascript/sri/mobile-examples/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
Error: TimeoutError: transforming /Users/hamazy/Documents/programming/javascript/sri/mobile-examples/index.ios.js took longer than 301 seconds.
You can adjust timeout via the 'transformTimeoutInterval' option
    at index.js:101:30
    at tryCallOne (/Users/hamazy/Documents/programming/javascript/sri/mobile-examples/node_modules/promise/lib/core.js:37:12)
    at /Users/hamazy/Documents/programming/javascript/sri/mobile-examples/node_modules/promise/lib/core.js:123:15
    at flush (/Users/hamazy/Documents/programming/javascript/sri/mobile-examples/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
```

Although @chandu0101 reported the same issue in facebook/react-native#6830 and it was already closed,  the problem still exists in the example. It would be nice if it runs right out of the box.

A possible solution would be [fix-transform-timeout branch in hamazy/sri](/hamazy/sri/tree/fix-transform-timeout) but I'm not sure the direction is ok. I will create a pull request if it's needed.

**Comment by chandu0101** [comment]
@hamazy  wow cool looks like you implemented Satya's suggestion!, please send PR  :)  , one small suggestion is rename `mobile-example.js` to `scalajs-output.js`

**Comment by hamazy** [comment]
@chandu0101 Ok, thanks. I created chandu0101/sri#39 with the file name changed.
